# Generated by Django 5.0.2 on 2025-10-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ticker_stockprice_sentimentscore_sentimenthistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('composite_score', models.FloatField(help_text='Final composite sentiment score from -100 to 100')),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('avg_base_sentiment', models.FloatField(help_text='Average base sentiment (-1 to 1)')),
                ('avg_surprise_factor', models.FloatField(help_text='Average surprise multiplier')),
                ('avg_novelty', models.FloatField(help_text='Average novelty score')),
                ('avg_source_credibility', models.FloatField(help_text='Average source credibility')),
                ('avg_recency_weight', models.FloatField(help_text='Average recency weight')),
                ('stock_price', models.DecimalField(decimal_places=2, help_text='Stock price at analysis time', max_digits=10)),
                ('price_open', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_change_percent', models.FloatField(blank=True, help_text='Price change percentage', null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('articles_analyzed', models.IntegerField(default=0)),
                ('cached_articles', models.IntegerField(default=0)),
                ('new_articles', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='sentimentscore',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Old Sentiment Score', 'verbose_name_plural': 'Old Sentiment Scores'},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Old Stock Price', 'verbose_name_plural': 'Old Stock Prices'},
        ),
        migrations.RemoveIndex(
            model_name='sentimentscore',
            name='api_sentime_ticker__172bd4_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='api_stockpr_ticker__708e8c_idx',
        ),
        migrations.AddField(
            model_name='sentimenthistory',
            name='total_analyses',
            field=models.IntegerField(default=0, help_text='Number of analysis runs'),
        ),
        migrations.AlterField(
            model_name='sentimentscore',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_sentiment_scores', to='api.ticker'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_stock_prices', to='api.ticker'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='api.ticker'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='analysis_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='api.analysisrun'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['ticker', '-timestamp'], name='api_analysi_ticker__f4b06a_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['-timestamp'], name='api_analysi_timesta_21b901_idx'),
        ),
    ]
