# Generated by Django 5.0.2 on 2025-10-20 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_analysisrun_alter_sentimentscore_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_score', models.FloatField(help_text='Individual ticker sentiment score')),
                ('market_cap_weight', models.FloatField(help_text='Market cap weight used (0.0 to 1.0)')),
                ('weighted_contribution', models.FloatField(help_text='Contribution to composite (score × weight)')),
                ('articles_analyzed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticker Contribution',
                'verbose_name_plural': 'Ticker Contributions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='article_type',
            field=models.CharField(db_index=True, default='company', max_length=20),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['article_type'], name='api_newsart_article_84bd23_idx'),
        ),
        migrations.AddField(
            model_name='tickercontribution',
            name='analysis_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker_contributions', to='api.analysisrun'),
        ),
        migrations.AddField(
            model_name='tickercontribution',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ticker'),
        ),
        migrations.AddIndex(
            model_name='tickercontribution',
            index=models.Index(fields=['analysis_run', 'ticker'], name='api_tickerc_analysi_607d69_idx'),
        ),
    ]
