# Generated by Django 5.0.2 on 2025-10-21 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tickercontribution_newsarticle_article_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='atr_14',
            field=models.FloatField(blank=True, help_text='ATR 14-period on 5-min chart', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='bb_lower',
            field=models.FloatField(blank=True, help_text='Bollinger Band lower band', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='bb_middle',
            field=models.FloatField(blank=True, help_text='Bollinger Band middle band (SMA)', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='bb_upper',
            field=models.FloatField(blank=True, help_text='Bollinger Band upper band', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='ema_20',
            field=models.FloatField(blank=True, help_text='Exponential Moving Average 20-period on 5-min', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='ema_9',
            field=models.FloatField(blank=True, help_text='Exponential Moving Average 9-period on 5-min', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='macd',
            field=models.FloatField(blank=True, help_text='MACD line', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='macd_histogram',
            field=models.FloatField(blank=True, help_text='MACD histogram', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='macd_signal',
            field=models.FloatField(blank=True, help_text='MACD signal line', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='qqq_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='QQQ ETF price at analysis time', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='rsi_14',
            field=models.FloatField(blank=True, help_text='RSI 14-period on 5-min chart (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='sma_20',
            field=models.FloatField(blank=True, help_text='Simple Moving Average 20-period on 5-min', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='sma_50',
            field=models.FloatField(blank=True, help_text='Simple Moving Average 50-period on 5-min', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='stoch_d',
            field=models.FloatField(blank=True, help_text='Stochastic %D line (signal)', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='stoch_k',
            field=models.FloatField(blank=True, help_text='Stochastic %K line', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='williams_r',
            field=models.FloatField(blank=True, help_text='Williams %R (-100 to 0)', null=True),
        ),
    ]
