# Generated by Django 5.0.2 on 2025-10-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_reddit_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='reddit_comments_analyzed',
            field=models.IntegerField(default=0, help_text='Number of Reddit comments analyzed'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='reddit_posts_analyzed',
            field=models.IntegerField(default=0, help_text='Number of Reddit posts analyzed'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='reddit_sentiment',
            field=models.FloatField(blank=True, help_text='Reddit/social media sentiment score (-100 to 100)', null=True),
        ),
    ]
