# Generated by Django 5.0.2 on 2025-10-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_add_reddit_sentiment_to_analysis_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='technical_composite_score',
            field=models.FloatField(blank=True, help_text='Technical indicators composite score (-100 to 100)', null=True),
        ),
    ]
