# Generated by Django 5.0.2 on 2025-10-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_technical_composite_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='analyst_buy',
            field=models.IntegerField(default=0, help_text='Total Buy recommendations'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analyst_hold',
            field=models.IntegerField(default=0, help_text='Total Hold recommendations'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analyst_recommendations_count',
            field=models.IntegerField(default=0, help_text='Total number of analyst recommendations analyzed'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analyst_recommendations_score',
            field=models.FloatField(blank=True, help_text='Analyst recommendations composite score (-100 to 100)', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analyst_sell',
            field=models.IntegerField(default=0, help_text='Total Sell recommendations'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analyst_strong_buy',
            field=models.IntegerField(default=0, help_text='Total Strong Buy recommendations'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='analyst_strong_sell',
            field=models.IntegerField(default=0, help_text='Total Strong Sell recommendations'),
        ),
    ]
