# Netlify configuration for Nasdaq Sentiment Tracker with Authentication

# SPA fallback - serve index.html for routes that don't exist
# This allows client-side routing while preserving access to actual files
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
